### ISSUE TITLE
NuGet packages

### ISSUE THREAD

**Issue by galvesribeiro** [berhir/SignalR.Modules#5]
Awesome work!

Do you plan to release it as NuGet packages?

Thanks!

**Comment by berhir** [comment]
I thought about it but didn't have the time yet. I can publish it as-is as a preview version to NuGet.
But I think it will require some cleanup and more testing to make it a re-usable library, that's why I didn't do it yet.

What do you think?

**Comment by berhir** [comment]
Hi @galvesribeiro, after thinking about it a bit more, I decided to not publish it as a NuGet package. I don't have the time to do all the things that are needed to publish it as a library. And I don't want to raise wrong expectations by pushing it to NuGet in the current state.
